config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
    end
  end
  match "/delayed_job", to: DelayedJobWeb, anchor: false, via: [:get, :post]
  # get 'tags/index'
  get '/tags' => 'tags#index'
  # get 'tags/show'
  get '/tags/:id' => 'tags#show', as: :tag

  # Admin related routes
  namespace :admin do

    resources :panel, only: [:index]
  end

  # Session related routes
  resource :session, only: [:new, :create, :destroy]

  # User related routes
  resources :users, only: [:new, :create]

  # resources :products do
  #   resources :reviews, only: [:create, :destroy, :edit, :update] do
  #     resources :loves, only: [:create, :destroy], shallow: true
  #   end
  # end

  resources :products do
    resources :likes, only: [:create, :destroy], shallow: true
    resources :favourites, only: [:create, :destroy], shallow: true
    resources :votes, only: [:create, :update, :destroy], shallow: true
    resources :reviews, only: [:create, :destroy, :edit, :update] do
      resources :loves, only: [:create, :destroy], shallow: true
      member do
        patch :toggle_hidden
        # toggle_hidden_product_review_path
        # POST	/products/:product_id/reviews/:id/toggle_hidden(.:format)
        # reviews#toggle_hidden
      end
    end
    resources :reviews, only: [], shallow: true do
        resources :review_votes, only: [:create, :update, :destroy], shallow: true
    end
  end


  # the line below defines a Rails route. The routes says here: if we receive
  # an HTTP, GET request with url `/` (home page) then handle the request with
  # the WelcomeController using the index action (method in the the controller)
  # `as: :home` will generate a url helper: home_path that maps to the same url

  # get('/products/new', to: 'products#new', as: :new_product)
  # post('/products/', to: 'products#create', as: :products)
  #
  # get('/products/:id', to: 'products#show', as: :product)
  # get('/products', to: 'products#index')
  #
  # delete('products/id', to: 'products#destroy' )
  #
  #
  # get('/products/:id/edit', to: 'products#edit', as: :edit_product)
  # patch('/products/:id', to: 'products#update')


  get('/', { to: 'welcome#index', as: :home })

  get('/about', { to: 'welcome#about' })

  get('/contact', { to: 'contact#create' })

  post('/contact', { to: 'contact#create' })
end

app/models/product.rb
class Product < ApplicationRecord
  # validation will be run before save
  has_many :reviews, dependent: :destroy

  has_many :likes, dependent: :destroy

  has_many :likers, through: :likes, source: :user

  has_many :favourites, dependent: :destroy

  has_many :favouriters, through: :favourites, source: :user

  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # belongs_to :user, optional: true
  belongs_to :user

  validates(
    :title,
    presence: {message: "must be given"},
    uniqueness: true,
    # case_sensitive: false
  )
  validates :price, numericality: {greater_than: 0}

  validates :description, presence: true, length: {minimum: 10}

  validate :reserved

  scope :search, -> (word){
   where("title ILIKE '%#{word}%' or description ILIKE '%#{word}%'")
  }


  # def self.search(key)
  #  where("title ILIKE '%#{word}%' or description ILIKE '%#{word}%'")
  # end

  # database method (writing a query with scope)

  # scope :price_gt_0, -> (){
  #   where("price > 0")
  # }


  validate :sale_price_must_be_less_than_or_equal_to_price

  def sale_price_must_be_less_than_or_equal_to_price
    if price.present? && sale_price.present? && sale_price > price
      errors.add(:sale_price, "can't be greater than price")
    end
  end

  # a method called on_sale? that returns true or false whether the product is on sale or not


  def on_sale?
    if price.present? && sale_price.present? && sale_price < price
       true
    end
  end


  def votes_result
    votes.where({ is_up: true }).count - votes.where({ is_up: false }).count
  end

  after_initialize :set_defaults
  before_validation :capitalize

  private
  def set_defaults
    self.price ||= 10
    self.sale_price ||= self.price
  end

  def capitalize
    self.title.try(:capitalize!)
  end

  def reserved
    if
      title.present? && title.downcase.include?('apple')||
      title.present? && title.downcase.include?('microsoft') ||
      title.present? && title.downcase.include?('sony')
      errors.add(:title, "The name is reserved!")
    end
  end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController

  before_action :authenticate_user!
  before_action :find_product, only: [:show, :destroy, :update]

    def index
    @products = Product.order(created_at: :desc)
        # render json: Product.all
        #  if u use jbuilder u don't need to use render but with serializer u need
    end

    def show
      render json: @product
    end

    def create
      product = Product.new(product_params)
      product.user = current_user

      if product.save
        render json: { id: product.id }
        # render json: params
      else
        render json: { error: product.errors.full_messages }
      end
    end

    def update
      if @product.update(product_params)
        render json: @product
      else
        render json: { error: @product.errors.full_messages }
      end
    end


    def destroy
      if @product.destroy
        # head :ok
        render json: { message: 'Successfully deleted!!!' }
      else
        head :bad_request
        # render json: { error: product.errors.full_messages }
      end
    end

  private

  def find_product
    @product = Product.find params[:id]
  end
  def product_params
     params.require(:product).permit(:title, :description, :price, :sale_price)
   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index, :edit]
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params

    @product.user = current_user

    if @product.save
      ProductsMailer.notify_product_owner(@product).deliver_now

      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product.price = @product.price.round(2)
    # <%= form.number_field :price, step: :any %>
    # @reviews = @product.reviews.order(created_at: :desc)
    @reviews = @product.reviews.sort{|b,a| a.review_votes_result <=> b.review_votes_result}

    @review = Review.new
    @user_like = current_user.likes.find_by_product_id(@product) if user_signed_in?
    @user_favourite = current_user.favourites.find_by_product_id(@product) if user_signed_in?
    @user_vote = current_user.votes.find_by_product_id(@product) if user_signed_in?

  end

  def index
    @liked = params[:liked]
    @favourited = params[:favourited]
      #this is get from application.html.erb `{liked: true}`
     if @liked
       @products = current_user.liked_products
     elsif @favourited
       @products = current_user.favourited_products
     else
       @products = Product.all.order(created_at: :desc)
     end
     respond_to do |format|
       format.html { render }
       format.json { render json: @products}
        # go to http://localhost:3000/products.json to show all the data
       format.xml { render xml: @products}
   end
  end

  def destroy
    @product.destroy
    redirect_to products_path, alert: 'Product deleted'
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product = Product.find params[:id]
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end


  private
  def product_params
    params.require(:product).permit(:title, :description, :price, { tag_ids: [] })
  end

  def find_product
    @product = Product.find params[:id]
  end

  def authorize_user!
    # When using cancancan methods like `can?`, it knows
    # the logged in user as long as the method `current_user`
    # is defined for controllers.

    unless can?(:crud, @product)
      flash[:alert] = "Access Denied!"
      redirect_to home_path
    end
  end
end

app/views/products/_form.html.erb
<div class="container">
  <div class="form">
    <%= form_for @product do |form| %>
      <% if @product.errors.present? %>
        <p><%= @product.errors.full_messages.join(', ') %></p>
      <% end %>

      <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>

      <div>
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class=" mt-2" >
        <%= form.label :price %>
        <%= form.number_field :price, step: :any %>
      </div>
      <%= form.collection_select(
        :tag_ids,
        Tag.order(:name),
        :id,
        :name,
        {},
        {
          multiple: true,
          class: 'chosen-select'
        }
      ) %>

        <div class=" mt-2">
          <%= form.submit "Create a Product", class: "btn btn-secondary btn-sm" %>
        </div>

    <% end %>
</div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
  <% if @liked %>
    <h3 >My Liked Products</h3>
    <% elsif @favourited %>
      <h3 >My Favourite Products</h3>
    <% else %>
      <h3>All Products</h3>
  <% end %>


  <% @products.each do |product| %>
    <div class="product-list-item">
      <%= link_to product.title, product_path(product) %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="contaienr">
    <h6> Product Form </h6>
  </div>
  <p><%= @product.title %></p>
  <p><%= @product.description %></p>
  <p>By <%= @product.user&.full_name || "[deleted]" %></p>
  <p>price:$ <%= @product.price %></p>
  <small>
    <strong>Tags:</strong>
    <% @product.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
    <% end %>
  </small>
  <div class="mt-2">
    <% if can?(:crud, @product) %>
    <%= link_to 'Edit', edit_product_path(@product) %>
      <%=
        link_to(
          'Delete',
          product_path(@product),
          method: :delete,
          data: {confirm: 'Are you sure?'}
        )
      %>
    <% end %>
  </div>


<div class="">
  <% if can?(:like, @product) %>
  <% if @user_like %>
    <%= link_to fa_icon("thumbs-up 1x"), like_path(@user_like), method: :delete %>
  <% else %>
    <%= link_to fa_icon("thumbs-o-up 1x"), product_likes_path(@product), method: :post %>
  <% end %>
<% end %>
(<%= pluralize(@product.likes.count, 'like') %>)


<% if can?(:favourite, @product) %>
   <% if @user_favourite %>
     <%= link_to fa_icon("heart"), favourite_path(@user_favourite), method: :delete, class: "text-danger" %>
   <% else %>
     <%= link_to fa_icon("heart-o"), product_favourites_path(@product), method: :post, class: "text-danger" %>
   <% end %>
 <% end %>
 (<%= pluralize(@product.favourites.count, 'favourite') %>)
<%= product_vote(@user_vote, @product).html_safe if user_signed_in? %>
</div>
</div>
<hr>

<div class="container">
  <div class="form">
    <h6>Review Form</h6>
    <%= form_for [@product, @review] do |f| %>
      <% if @review.errors.present? %>
        <p>
          <%= @review.errors.full_messages.join(', ') %>
        </p>
      <% end %>

      <div>
        <div>
          <%= f.label :comments %>
          <%= f.text_area :body, class: 'form-control' %>
        </div>
        <p class=" mt-2"> Rating: <%= f.number_field :rating , in:1..5 %></p>
      </div>

      <div class=" mt-2">
        <%= f.submit "Create a Review", class: "btn btn-secondary btn-sm" %>
      </div>
    <% end %>
    <hr>
  </div>
</div>

<div class="container">
  <h6> Review </h6>
  <div class="review-list">
    <div>
      <% @reviews.each do |review| %>
        <% if can?(:read, review) %>

          <div <% if review.is_hidden %> style="color:lightgrey"<% end %>>

            <div>
              <p><strong>Rating:</strong> <%= review.rating %></p>
              <p><strong>Reviews:</strong> <%= review.body %></p>
              <p><strong>User:</strong><%= review.user.full_name %></p>
              <p><strong>Created At:</strong> <%= time_ago_in_words(review.created_at) %> ago</p>

              <% if can?(:crud, @product) %>
                <%= link_to 'Hide/ Unhide', toggle_hidden_product_review_path(@product, review),
                method: :patch %>
             <% end %>

              <% if can?(:crud, review) %>
                <%= link_to 'Edit', edit_product_review_path(@product, review) %>
                <%=
                  link_to(
                    'Delete',
                    product_review_path(@product, review),
                    method: :delete,
                    data: {confirm: 'Are you sure?'}
                  )
                %>
              <% end %>
            </div>
          </div>

          <% if can?(:love, review) %>
            <% if review.loves.find_by_user_id(current_user) %>
              <%= link_to fa_icon("star"), love_path(review.loves.find_by_user_id(current_user)), method: :delete, class:"text-warning" %>

            <% else %>
              <%= link_to fa_icon("star-o"), product_review_loves_path(@product, review), method: :post, class:"text-warning"  %>
            <% end %>
          <% end %>

          <% if can?(:review_vote, review) %>
            <% user_review_vote = current_user.review_votes.find_by_review_id(review) %>
            <%= review_vote(user_review_vote, review).html_safe if user_signed_in? %>
          <%else %>
            <span>
              Review Votes: <%= review.review_votes_result %>
            </span>
          <% end %>

        <% end %>

      <% end %>
    </div>
  </div>
</div>