config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
    end
  end
  match "/delayed_job", to: DelayedJobWeb, anchor: false, via: [:get, :post]
  # get 'tags/index'
  get '/tags' => 'tags#index'
  # get 'tags/show'
  get '/tags/:id' => 'tags#show', as: :tag

  # Admin related routes
  namespace :admin do

    resources :panel, only: [:index]
  end

  # Session related routes
  resource :session, only: [:new, :create, :destroy]

  # User related routes
  resources :users, only: [:new, :create]

  # resources :products do
  #   resources :reviews, only: [:create, :destroy, :edit, :update] do
  #     resources :loves, only: [:create, :destroy], shallow: true
  #   end
  # end

  resources :products do
    resources :likes, only: [:create, :destroy], shallow: true
    resources :favourites, only: [:create, :destroy], shallow: true
    resources :votes, only: [:create, :update, :destroy], shallow: true
    resources :reviews, only: [:create, :destroy, :edit, :update] do
      resources :loves, only: [:create, :destroy], shallow: true
      member do
        patch :toggle_hidden
        # toggle_hidden_product_review_path
        # POST	/products/:product_id/reviews/:id/toggle_hidden(.:format)
        # reviews#toggle_hidden
      end
    end
    resources :reviews, only: [], shallow: true do
        resources :review_votes, only: [:create, :update, :destroy], shallow: true
    end
  end


  # the line below defines a Rails route. The routes says here: if we receive
  # an HTTP, GET request with url `/` (home page) then handle the request with
  # the WelcomeController using the index action (method in the the controller)
  # `as: :home` will generate a url helper: home_path that maps to the same url

  # get('/products/new', to: 'products#new', as: :new_product)
  # post('/products/', to: 'products#create', as: :products)
  #
  # get('/products/:id', to: 'products#show', as: :product)
  # get('/products', to: 'products#index')
  #
  # delete('products/id', to: 'products#destroy' )
  #
  #
  # get('/products/:id/edit', to: 'products#edit', as: :edit_product)
  # patch('/products/:id', to: 'products#update')


  get('/', { to: 'welcome#index', as: :home })

  get('/about', { to: 'welcome#about' })

  get('/contact', { to: 'contact#create' })

  post('/contact', { to: 'contact#create' })
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= javascript_include_tag 'application' %>
    </head>


  <body>

      <nav style="margin: 10px; font-size: 10px">
        <a href="/">Home</a>
        |
        <%= link_to('About Us', about_path, { id: 'abc', class: 'xyz' }) %>
        |
        <%= link_to 'Contact Us', contact_path %>

        |
        <%= link_to 'New Product', new_product_path %>
        |
        <%= link_to 'All Products', products_path %>
        |
        <% if user_signed_in? %>
        <%= link_to 'My Liked Products', products_path({liked: true}) %>
        <% end %>
        |
        <% if user_signed_in? %>
        <%= link_to 'My Favourited Products', products_path({favourited: true}) %>
        <% end %>
        |
        <% if user_signed_in? %>
        <%= link_to 'Tags', tags_path %>
        <% end %>
        |

      <% if user_signed_in? %>
        <span>Hello, <%= current_user.first_name %>!</span>
        |
        <% if current_user.is_admin? %>

        <%= link_to 'Dashboard', admin_panel_index_path %>
      <% end %>
        |
        <%= link_to(
          'Sign Out',
          session_path,
          method: :delete,
          data: {confirm: 'Do you really want to sign out?'}
        ) %>
      <% else %>
        <%= link_to 'Sign In', new_session_path %>
        |
        <%= link_to 'Sign Up', new_user_path %>
      <% end %>


      <% if flash[:notice].present? || flash[:alert].present? %>
        <div class="flash-message">
          <p><%= flash[:notice] || flash[:alert] %></p>
        </div>
      <% end %>

    <hr>
    <%= yield %>
  </body>
</html>